# Generated by Django 3.1.4 on 2021-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
    ]
