# Generated by Django 3.1.4 on 2021-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211016_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
