# Generated by Django 3.1.4 on 2021-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211016_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
