# Generated by Django 3.1.4 on 2021-11-26 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_auto_20211126_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('discount_amount', models.FloatField()),
                ('discount_type', models.CharField(max_length=200)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount', models.FloatField()),
                ('redemption_date', models.DateTimeField()),
                ('coupon_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
