# Generated by Django 3.1.4 on 2021-11-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_coupon_couponredemption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponredemption',
            old_name='user',
            new_name='user_id',
        ),
    ]
