# Generated by Django 3.1.4 on 2021-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20211126_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
