# Generated by Django 3.1.4 on 2021-11-29 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_couponredemption_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='filtering_history',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
