# Generated by Django 3.1.4 on 2022-01-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20220107_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='createdAt',
            field=models.DateField(),
        ),
    ]
