# Generated by Django 3.1.4 on 2022-01-08 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='temp_user_otp',
            field=models.CharField(default=datetime.datetime(2022, 1, 8, 15, 22, 5, 988064, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
