# Generated by Django 3.1.4 on 2022-01-08 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_tempuser_temp_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='temp_user_password',
            field=models.CharField(default=datetime.datetime(2022, 1, 8, 15, 31, 13, 669023, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
