# Generated by Django 3.1.4 on 2022-01-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_tempuser_temp_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
