# Generated by Django 3.1.4 on 2022-01-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
